---
name: ğŸ•Šï¸ Release Workflow

on:
  push:
    branches:
      - main

# Limit workflow to one job per branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  STABLE_PYTHON_VERSION: '3.9'
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  release-workflow:
    name: ğŸ¹ Release Workflow
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“© Checkout the source w/ full depth(for tags and SCM)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ Setup Python ${{ env.STABLE_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.STABLE_PYTHON_VERSION }}

      - name: ğŸ§± Build wheel
        run: |
          pip install wheel
          pip install --upgrade pip wheel
          pip install --editable .
          hatch build --clean --target wheel

      - name: ğŸ¦ Release wheel
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ SECRETS.PYPI_TOKEN }}
          packages_dir: dist
          verbose: true
